// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwzNaKurqQYqmibPbga6RWqHMTaMfv72o',
    appId: '1:605911184316:web:b77c115eb0cf488676b1b9',
    messagingSenderId: '605911184316',
    projectId: 'ecommercemza',
    authDomain: 'ecommercemza.firebaseapp.com',
    storageBucket: 'ecommercemza.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1F8RQCDD1QWxql4CNcKFsEGSxbyTOngc',
    appId: '1:605911184316:android:3bf36001e6cf388876b1b9',
    messagingSenderId: '605911184316',
    projectId: 'ecommercemza',
    storageBucket: 'ecommercemza.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7CTPp3fVW_djr_uOq3IsQEKfVgtcsH88',
    appId: '1:605911184316:ios:9afe266474ca283376b1b9',
    messagingSenderId: '605911184316',
    projectId: 'ecommercemza',
    storageBucket: 'ecommercemza.firebasestorage.app',
    iosBundleId: 'com.mza.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7CTPp3fVW_djr_uOq3IsQEKfVgtcsH88',
    appId: '1:605911184316:ios:9afe266474ca283376b1b9',
    messagingSenderId: '605911184316',
    projectId: 'ecommercemza',
    storageBucket: 'ecommercemza.firebasestorage.app',
    iosBundleId: 'com.mza.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwzNaKurqQYqmibPbga6RWqHMTaMfv72o',
    appId: '1:605911184316:web:9a9d3212423abbd276b1b9',
    messagingSenderId: '605911184316',
    projectId: 'ecommercemza',
    authDomain: 'ecommercemza.firebaseapp.com',
    storageBucket: 'ecommercemza.firebasestorage.app',
  );
}
